<?php

namespace Database\Seeders;

use App\Models\KabKota;
use App\Models\Provinsi;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KabKotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kabkot = [
            ['id' => '1101', 'provinsi_id' => '11', 'nama' => 'KAB. ACEH SELATAN', 'email_info_penetapan' => null],
            ['id' => '1102', 'provinsi_id' => '11', 'nama' => 'KAB. ACEH TENGGARA', 'email_info_penetapan' => null],
            ['id' => '1103', 'provinsi_id' => '11', 'nama' => 'KAB. ACEH TIMUR', 'email_info_penetapan' => null],
            ['id' => '1104', 'provinsi_id' => '11', 'nama' => 'KAB. ACEH TENGAH', 'email_info_penetapan' => null],
            ['id' => '1105', 'provinsi_id' => '11', 'nama' => 'KAB. ACEH BARAT', 'email_info_penetapan' => null],
            ['id' => '1106', 'provinsi_id' => '11', 'nama' => 'KAB. ACEH BESAR', 'email_info_penetapan' => null],
            ['id' => '1107', 'provinsi_id' => '11', 'nama' => 'KAB. PIDIE', 'email_info_penetapan' => null],
            ['id' => '1108', 'provinsi_id' => '11', 'nama' => 'KAB. ACEH UTARA', 'email_info_penetapan' => null],
            ['id' => '1109', 'provinsi_id' => '11', 'nama' => 'KAB. SIMEULUE', 'email_info_penetapan' => null],
            ['id' => '1110', 'provinsi_id' => '11', 'nama' => 'KAB. ACEH SINGKIL', 'email_info_penetapan' => null],
            ['id' => '1111', 'provinsi_id' => '11', 'nama' => 'KAB. BIREUEN', 'email_info_penetapan' => null],
            ['id' => '1112', 'provinsi_id' => '11', 'nama' => 'KAB. ACEH BARAT DAYA', 'email_info_penetapan' => null],
            ['id' => '1113', 'provinsi_id' => '11', 'nama' => 'KAB. GAYO LUES', 'email_info_penetapan' => null],
            ['id' => '1114', 'provinsi_id' => '11', 'nama' => 'KAB. ACEH JAYA', 'email_info_penetapan' => null],
            ['id' => '1115', 'provinsi_id' => '11', 'nama' => 'KAB. NAGAN RAYA', 'email_info_penetapan' => null],
            ['id' => '1116', 'provinsi_id' => '11', 'nama' => 'KAB. ACEH TAMIANG', 'email_info_penetapan' => null],
            ['id' => '1117', 'provinsi_id' => '11', 'nama' => 'KAB. BENER MERIAH', 'email_info_penetapan' => null],
            ['id' => '1118', 'provinsi_id' => '11', 'nama' => 'KAB. PIDIE JAYA', 'email_info_penetapan' => null],
            ['id' => '1171', 'provinsi_id' => '11', 'nama' => 'KOTA BANDA ACEH', 'email_info_penetapan' => null],
            ['id' => '1172', 'provinsi_id' => '11', 'nama' => 'KOTA SABANG', 'email_info_penetapan' => null],
            ['id' => '1173', 'provinsi_id' => '11', 'nama' => 'KOTA LHOKSEUMAWE', 'email_info_penetapan' => null],
            ['id' => '1174', 'provinsi_id' => '11', 'nama' => 'KOTA LANGSA', 'email_info_penetapan' => null],
            ['id' => '1175', 'provinsi_id' => '11', 'nama' => 'KOTA SUBULUSSALAM', 'email_info_penetapan' => null],
            ['id' => '1201', 'provinsi_id' => '12', 'nama' => 'KAB. TAPANULI TENGAH', 'email_info_penetapan' => null],
            ['id' => '1202', 'provinsi_id' => '12', 'nama' => 'KAB. TAPANULI UTARA', 'email_info_penetapan' => null],
            ['id' => '1203', 'provinsi_id' => '12', 'nama' => 'KAB. TAPANULI SELATAN', 'email_info_penetapan' => null],
            ['id' => '1204', 'provinsi_id' => '12', 'nama' => 'KAB. NIAS', 'email_info_penetapan' => null],
            ['id' => '1205', 'provinsi_id' => '12', 'nama' => 'KAB. LANGKAT', 'email_info_penetapan' => null],
            ['id' => '1206', 'provinsi_id' => '12', 'nama' => 'KAB. KARO', 'email_info_penetapan' => null],
            ['id' => '1207', 'provinsi_id' => '12', 'nama' => 'KAB. DELI SERDANG', 'email_info_penetapan' => null],
            ['id' => '1208', 'provinsi_id' => '12', 'nama' => 'KAB. SIMALUNGUN', 'email_info_penetapan' => null],
            ['id' => '1209', 'provinsi_id' => '12', 'nama' => 'KAB. ASAHAN', 'email_info_penetapan' => null],
            ['id' => '1210', 'provinsi_id' => '12', 'nama' => 'KAB. LABUHANBATU', 'email_info_penetapan' => null],
            ['id' => '1211', 'provinsi_id' => '12', 'nama' => 'KAB. DAIRI', 'email_info_penetapan' => null],
            ['id' => '1212', 'provinsi_id' => '12', 'nama' => 'KAB. TOBA SAMOSIR', 'email_info_penetapan' => null],
            ['id' => '1213', 'provinsi_id' => '12', 'nama' => 'KAB. MANDAILING NATAL', 'email_info_penetapan' => null],
            ['id' => '1214', 'provinsi_id' => '12', 'nama' => 'KAB. NIAS SELATAN', 'email_info_penetapan' => null],
            ['id' => '1215', 'provinsi_id' => '12', 'nama' => 'KAB. PAKPAK BHARAT', 'email_info_penetapan' => null],
            ['id' => '1216', 'provinsi_id' => '12', 'nama' => 'KAB. HUMBANG HASUNDUTAN', 'email_info_penetapan' => null],
            ['id' => '1217', 'provinsi_id' => '12', 'nama' => 'KAB. SAMOSIR', 'email_info_penetapan' => null],
            ['id' => '1218', 'provinsi_id' => '12', 'nama' => 'KAB. SERDANG BEDAGAI', 'email_info_penetapan' => null],
            ['id' => '1219', 'provinsi_id' => '12', 'nama' => 'KAB. BATU BARA', 'email_info_penetapan' => null],
            ['id' => '1220', 'provinsi_id' => '12', 'nama' => 'KAB. PADANG LAWAS UTARA', 'email_info_penetapan' => null],
            ['id' => '1221', 'provinsi_id' => '12', 'nama' => 'KAB. PADANG LAWAS', 'email_info_penetapan' => null],
            ['id' => '1222', 'provinsi_id' => '12', 'nama' => 'KAB. LABUHANBATU SELATAN', 'email_info_penetapan' => null],
            ['id' => '1223', 'provinsi_id' => '12', 'nama' => 'KAB. LABUHANBATU UTARA', 'email_info_penetapan' => null],
            ['id' => '1224', 'provinsi_id' => '12', 'nama' => 'KAB. NIAS UTARA', 'email_info_penetapan' => null],
            ['id' => '1225', 'provinsi_id' => '12', 'nama' => 'KAB. NIAS BARAT', 'email_info_penetapan' => null],
            ['id' => '1271', 'provinsi_id' => '12', 'nama' => 'KOTA MEDAN', 'email_info_penetapan' => null],
            ['id' => '1272', 'provinsi_id' => '12', 'nama' => 'KOTA PEMATANGSIANTAR', 'email_info_penetapan' => null],
            ['id' => '1273', 'provinsi_id' => '12', 'nama' => 'KOTA SIBOLGA', 'email_info_penetapan' => null],
            ['id' => '1274', 'provinsi_id' => '12', 'nama' => 'KOTA TANJUNG BALAI', 'email_info_penetapan' => null],
            ['id' => '1275', 'provinsi_id' => '12', 'nama' => 'KOTA BINJAI', 'email_info_penetapan' => null],
            ['id' => '1276', 'provinsi_id' => '12', 'nama' => 'KOTA TEBING TINGGI', 'email_info_penetapan' => null],
            ['id' => '1277', 'provinsi_id' => '12', 'nama' => 'KOTA PADANG SIDEMPUAN', 'email_info_penetapan' => null],
            ['id' => '1278', 'provinsi_id' => '12', 'nama' => 'KOTA GUNUNGSITOLI', 'email_info_penetapan' => null],
            ['id' => '1301', 'provinsi_id' => '13', 'nama' => 'KAB. PESISIR SELATAN', 'email_info_penetapan' => null],
            ['id' => '1302', 'provinsi_id' => '13', 'nama' => 'KAB. SOLOK', 'email_info_penetapan' => null],
            ['id' => '1303', 'provinsi_id' => '13', 'nama' => 'KAB. SIJUNJUNG', 'email_info_penetapan' => null],
            ['id' => '1304', 'provinsi_id' => '13', 'nama' => 'KAB. TANAH DATAR', 'email_info_penetapan' => null],
            ['id' => '1305', 'provinsi_id' => '13', 'nama' => 'KAB. PADANG PARIAMAN', 'email_info_penetapan' => null],
            ['id' => '1306', 'provinsi_id' => '13', 'nama' => 'KAB. AGAM', 'email_info_penetapan' => null],
            ['id' => '1307', 'provinsi_id' => '13', 'nama' => 'KAB. LIMA PULUH KOTA', 'email_info_penetapan' => null],
            ['id' => '1308', 'provinsi_id' => '13', 'nama' => 'KAB. PASAMAN', 'email_info_penetapan' => null],
            ['id' => '1309', 'provinsi_id' => '13', 'nama' => 'KAB. KEPULAUAN MENTAWAI', 'email_info_penetapan' => null],
            ['id' => '1310', 'provinsi_id' => '13', 'nama' => 'KAB. DHARMASRAYA', 'email_info_penetapan' => null],
            ['id' => '1311', 'provinsi_id' => '13', 'nama' => 'KAB. SOLOK SELATAN', 'email_info_penetapan' => null],
            ['id' => '1312', 'provinsi_id' => '13', 'nama' => 'KAB. PASAMAN BARAT', 'email_info_penetapan' => null],
            ['id' => '1371', 'provinsi_id' => '13', 'nama' => 'KOTA PADANG', 'email_info_penetapan' => null],
            ['id' => '1372', 'provinsi_id' => '13', 'nama' => 'KOTA SOLOK', 'email_info_penetapan' => null],
            ['id' => '1373', 'provinsi_id' => '13', 'nama' => 'KOTA SAWAHLUNTO', 'email_info_penetapan' => null],
            ['id' => '1374', 'provinsi_id' => '13', 'nama' => 'KOTA PADANG PANJANG', 'email_info_penetapan' => null],
            ['id' => '1375', 'provinsi_id' => '13', 'nama' => 'KOTA BUKITTINGGI', 'email_info_penetapan' => null],
            ['id' => '1376', 'provinsi_id' => '13', 'nama' => 'KOTA PAYAKUMBUH', 'email_info_penetapan' => null],
            ['id' => '1377', 'provinsi_id' => '13', 'nama' => 'KOTA PARIAMAN', 'email_info_penetapan' => null],
            ['id' => '1401', 'provinsi_id' => '14', 'nama' => 'KAB. KAMPAR', 'email_info_penetapan' => null],
            ['id' => '1402', 'provinsi_id' => '14', 'nama' => 'KAB. INDRAGIRI HULU', 'email_info_penetapan' => null],
            ['id' => '1403', 'provinsi_id' => '14', 'nama' => 'KAB. BENGKALIS', 'email_info_penetapan' => null],
            ['id' => '1404', 'provinsi_id' => '14', 'nama' => 'KAB. INDRAGIRI HILIR', 'email_info_penetapan' => null],
            ['id' => '1405', 'provinsi_id' => '14', 'nama' => 'KAB. PELALAWAN', 'email_info_penetapan' => null],
            ['id' => '1406', 'provinsi_id' => '14', 'nama' => 'KAB. ROKAN HULU', 'email_info_penetapan' => null],
            ['id' => '1407', 'provinsi_id' => '14', 'nama' => 'KAB. ROKAN HILIR', 'email_info_penetapan' => null],
            ['id' => '1408', 'provinsi_id' => '14', 'nama' => 'KAB. SIAK', 'email_info_penetapan' => null],
            ['id' => '1409', 'provinsi_id' => '14', 'nama' => 'KAB. KUANTAN SINGINGI', 'email_info_penetapan' => null],
            ['id' => '1410', 'provinsi_id' => '14', 'nama' => 'KAB. KEPULAUAN MERANTI', 'email_info_penetapan' => null],
            ['id' => '1471', 'provinsi_id' => '14', 'nama' => 'KOTA PEKANBARU', 'email_info_penetapan' => null],
            ['id' => '1472', 'provinsi_id' => '14', 'nama' => 'KOTA DUMAI', 'email_info_penetapan' => null],
            ['id' => '1501', 'provinsi_id' => '15', 'nama' => 'KAB. KERINCI', 'email_info_penetapan' => null],
            ['id' => '1502', 'provinsi_id' => '15', 'nama' => 'KAB. MERANGIN', 'email_info_penetapan' => null],
            ['id' => '1503', 'provinsi_id' => '15', 'nama' => 'KAB. SAROLANGUN', 'email_info_penetapan' => null],
            ['id' => '1504', 'provinsi_id' => '15', 'nama' => 'KAB. BATANGHARI', 'email_info_penetapan' => null],
            ['id' => '1505', 'provinsi_id' => '15', 'nama' => 'KAB. MUARO JAMBI', 'email_info_penetapan' => null],
            ['id' => '1506', 'provinsi_id' => '15', 'nama' => 'KAB. TANJUNG JABUNG BARAT', 'email_info_penetapan' => null],
            ['id' => '1507', 'provinsi_id' => '15', 'nama' => 'KAB. TANJUNG JABUNG TIMUR', 'email_info_penetapan' => null],
            ['id' => '1508', 'provinsi_id' => '15', 'nama' => 'KAB. BUNGO', 'email_info_penetapan' => null],
            ['id' => '1509', 'provinsi_id' => '15', 'nama' => 'KAB. TEBO', 'email_info_penetapan' => null],
            ['id' => '1571', 'provinsi_id' => '15', 'nama' => 'KOTA JAMBI', 'email_info_penetapan' => null],
            ['id' => '1572', 'provinsi_id' => '15', 'nama' => 'KOTA SUNGAI PENUH', 'email_info_penetapan' => null],
            ['id' => '1601', 'provinsi_id' => '16', 'nama' => 'KAB. OGAN KOMERING ULU', 'email_info_penetapan' => null],
            ['id' => '1602', 'provinsi_id' => '16', 'nama' => 'KAB. OGAN KOMERING ILIR', 'email_info_penetapan' => null],
            ['id' => '1603', 'provinsi_id' => '16', 'nama' => 'KAB. MUARA ENIM', 'email_info_penetapan' => null],
            ['id' => '1604', 'provinsi_id' => '16', 'nama' => 'KAB. LAHAT', 'email_info_penetapan' => null],
            ['id' => '1605', 'provinsi_id' => '16', 'nama' => 'KAB. MUSI RAWAS', 'email_info_penetapan' => null],
            ['id' => '1606', 'provinsi_id' => '16', 'nama' => 'KAB. MUSI BANYUASIN', 'email_info_penetapan' => null],
            ['id' => '1607', 'provinsi_id' => '16', 'nama' => 'KAB. BANYUASIN', 'email_info_penetapan' => null],
            ['id' => '1608', 'provinsi_id' => '16', 'nama' => 'KAB. OGAN KOMERING ULU TIMUR', 'email_info_penetapan' => null],
            ['id' => '1609', 'provinsi_id' => '16', 'nama' => 'KAB. OGAN KOMERING ULU SELATAN', 'email_info_penetapan' => null],
            ['id' => '1610', 'provinsi_id' => '16', 'nama' => 'KAB. OGAN ILIR', 'email_info_penetapan' => null],
            ['id' => '1611', 'provinsi_id' => '16', 'nama' => 'KAB. EMPAT LAWANG', 'email_info_penetapan' => null],
            ['id' => '1612', 'provinsi_id' => '16', 'nama' => 'KAB. PENUKAL ABAB LEMATANG ILIR', 'email_info_penetapan' => null],
            ['id' => '1613', 'provinsi_id' => '16', 'nama' => 'KAB. MUSI RAWAS UTARA', 'email_info_penetapan' => null],
            ['id' => '1671', 'provinsi_id' => '16', 'nama' => 'KOTA PALEMBANG', 'email_info_penetapan' => null],
            ['id' => '1672', 'provinsi_id' => '16', 'nama' => 'KOTA PAGAR ALAM', 'email_info_penetapan' => null],
            ['id' => '1673', 'provinsi_id' => '16', 'nama' => 'KOTA LUBUK LINGGAU', 'email_info_penetapan' => null],
            ['id' => '1674', 'provinsi_id' => '16', 'nama' => 'KOTA PRABUMULIH', 'email_info_penetapan' => null],
            ['id' => '1701', 'provinsi_id' => '17', 'nama' => 'KAB. BENGKULU SELATAN', 'email_info_penetapan' => null],
            ['id' => '1702', 'provinsi_id' => '17', 'nama' => 'KAB. REJANG LEBONG', 'email_info_penetapan' => null],
            ['id' => '1703', 'provinsi_id' => '17', 'nama' => 'KAB. BENGKULU UTARA', 'email_info_penetapan' => null],
            ['id' => '1704', 'provinsi_id' => '17', 'nama' => 'KAB. KAUR', 'email_info_penetapan' => null],
            ['id' => '1705', 'provinsi_id' => '17', 'nama' => 'KAB. SELUMA', 'email_info_penetapan' => null],
            ['id' => '1706', 'provinsi_id' => '17', 'nama' => 'KAB. MUKO MUKO', 'email_info_penetapan' => null],
            ['id' => '1707', 'provinsi_id' => '17', 'nama' => 'KAB. LEBONG', 'email_info_penetapan' => null],
            ['id' => '1708', 'provinsi_id' => '17', 'nama' => 'KAB. KEPAHIANG', 'email_info_penetapan' => null],
            ['id' => '1709', 'provinsi_id' => '17', 'nama' => 'KAB. BENGKULU TENGAH', 'email_info_penetapan' => null],
            ['id' => '1771', 'provinsi_id' => '17', 'nama' => 'KOTA BENGKULU', 'email_info_penetapan' => null],
            ['id' => '1801', 'provinsi_id' => '18', 'nama' => 'KAB. LAMPUNG SELATAN', 'email_info_penetapan' => null],
            ['id' => '1802', 'provinsi_id' => '18', 'nama' => 'KAB. LAMPUNG TENGAH', 'email_info_penetapan' => null],
            ['id' => '1803', 'provinsi_id' => '18', 'nama' => 'KAB. LAMPUNG UTARA', 'email_info_penetapan' => null],
            ['id' => '1804', 'provinsi_id' => '18', 'nama' => 'KAB. LAMPUNG BARAT', 'email_info_penetapan' => null],
            ['id' => '1805', 'provinsi_id' => '18', 'nama' => 'KAB. TULANG BAWANG', 'email_info_penetapan' => null],
            ['id' => '1806', 'provinsi_id' => '18', 'nama' => 'KAB. TANGGAMUS', 'email_info_penetapan' => null],
            ['id' => '1807', 'provinsi_id' => '18', 'nama' => 'KAB. LAMPUNG TIMUR', 'email_info_penetapan' => null],
            ['id' => '1808', 'provinsi_id' => '18', 'nama' => 'KAB. WAY KANAN', 'email_info_penetapan' => null],
            ['id' => '1809', 'provinsi_id' => '18', 'nama' => 'KAB. PESAWARAN', 'email_info_penetapan' => null],
            ['id' => '1810', 'provinsi_id' => '18', 'nama' => 'KAB. PRINGSEWU', 'email_info_penetapan' => null],
            ['id' => '1811', 'provinsi_id' => '18', 'nama' => 'KAB. MESUJI', 'email_info_penetapan' => null],
            ['id' => '1812', 'provinsi_id' => '18', 'nama' => 'KAB. TULANG BAWANG BARAT', 'email_info_penetapan' => null],
            ['id' => '1813', 'provinsi_id' => '18', 'nama' => 'KAB. PESISIR BARAT', 'email_info_penetapan' => null],
            ['id' => '1871', 'provinsi_id' => '18', 'nama' => 'KOTA BANDAR LAMPUNG', 'email_info_penetapan' => null],
            ['id' => '1872', 'provinsi_id' => '18', 'nama' => 'KOTA METRO', 'email_info_penetapan' => null],
            ['id' => '1901', 'provinsi_id' => '19', 'nama' => 'KAB. BANGKA', 'email_info_penetapan' => null],
            ['id' => '1902', 'provinsi_id' => '19', 'nama' => 'KAB. BELITUNG', 'email_info_penetapan' => null],
            ['id' => '1903', 'provinsi_id' => '19', 'nama' => 'KAB. BANGKA SELATAN', 'email_info_penetapan' => null],
            ['id' => '1904', 'provinsi_id' => '19', 'nama' => 'KAB. BANGKA TENGAH', 'email_info_penetapan' => null],
            ['id' => '1905', 'provinsi_id' => '19', 'nama' => 'KAB. BANGKA BARAT', 'email_info_penetapan' => null],
            ['id' => '1906', 'provinsi_id' => '19', 'nama' => 'KAB. BELITUNG TIMUR', 'email_info_penetapan' => null],
            ['id' => '1971', 'provinsi_id' => '19', 'nama' => 'KOTA PANGKAL PINANG', 'email_info_penetapan' => null],
            ['id' => '2101', 'provinsi_id' => '21', 'nama' => 'KAB. BINTAN', 'email_info_penetapan' => null],
            ['id' => '2102', 'provinsi_id' => '21', 'nama' => 'KAB. KARIMUN', 'email_info_penetapan' => null],
            ['id' => '2103', 'provinsi_id' => '21', 'nama' => 'KAB. NATUNA', 'email_info_penetapan' => null],
            ['id' => '2104', 'provinsi_id' => '21', 'nama' => 'KAB. LINGGA', 'email_info_penetapan' => null],
            ['id' => '2105', 'provinsi_id' => '21', 'nama' => 'KAB. KEPULAUAN ANAMBAS', 'email_info_penetapan' => null],
            ['id' => '2171', 'provinsi_id' => '21', 'nama' => 'KOTA BATAM', 'email_info_penetapan' => null],
            ['id' => '2172', 'provinsi_id' => '21', 'nama' => 'KOTA TANJUNG PINANG', 'email_info_penetapan' => null],
            ['id' => '3101', 'provinsi_id' => '31', 'nama' => 'KAB. ADM. KEP. SERIBU', 'email_info_penetapan' => null],
            ['id' => '3171', 'provinsi_id' => '31', 'nama' => 'KOTA ADM. JAKARTA PUSAT', 'email_info_penetapan' => null],
            ['id' => '3172', 'provinsi_id' => '31', 'nama' => 'KOTA ADM. JAKARTA UTARA', 'email_info_penetapan' => null],
            ['id' => '3173', 'provinsi_id' => '31', 'nama' => 'KOTA ADM. JAKARTA BARAT', 'email_info_penetapan' => null],
            ['id' => '3174', 'provinsi_id' => '31', 'nama' => 'KOTA ADM. JAKARTA SELATAN', 'email_info_penetapan' => null],
            ['id' => '3175', 'provinsi_id' => '31', 'nama' => 'KOTA ADM. JAKARTA TIMUR', 'email_info_penetapan' => null],
            ['id' => '3201', 'provinsi_id' => '32', 'nama' => 'KAB. BOGOR', 'email_info_penetapan' => null],
            ['id' => '3202', 'provinsi_id' => '32', 'nama' => 'KAB. SUKABUMI', 'email_info_penetapan' => null],
            ['id' => '3203', 'provinsi_id' => '32', 'nama' => 'KAB. CIANJUR', 'email_info_penetapan' => null],
            ['id' => '3204', 'provinsi_id' => '32', 'nama' => 'KAB. BANDUNG', 'email_info_penetapan' => null],
            ['id' => '3205', 'provinsi_id' => '32', 'nama' => 'KAB. GARUT', 'email_info_penetapan' => null],
            ['id' => '3206', 'provinsi_id' => '32', 'nama' => 'KAB. TASIKMALAYA', 'email_info_penetapan' => null],
            ['id' => '3207', 'provinsi_id' => '32', 'nama' => 'KAB. CIAMIS', 'email_info_penetapan' => null],
            ['id' => '3208', 'provinsi_id' => '32', 'nama' => 'KAB. KUNINGAN', 'email_info_penetapan' => null],
            ['id' => '3209', 'provinsi_id' => '32', 'nama' => 'KAB. CIREBON', 'email_info_penetapan' => null],
            ['id' => '3210', 'provinsi_id' => '32', 'nama' => 'KAB. MAJALENGKA', 'email_info_penetapan' => null],
            ['id' => '3211', 'provinsi_id' => '32', 'nama' => 'KAB. SUMEDANG', 'email_info_penetapan' => null],
            ['id' => '3212', 'provinsi_id' => '32', 'nama' => 'KAB. INDRAMAYU', 'email_info_penetapan' => null],
            ['id' => '3213', 'provinsi_id' => '32', 'nama' => 'KAB. SUBANG', 'email_info_penetapan' => null],
            ['id' => '3214', 'provinsi_id' => '32', 'nama' => 'KAB. PURWAKARTA', 'email_info_penetapan' => null],
            ['id' => '3215', 'provinsi_id' => '32', 'nama' => 'KAB. KARAWANG', 'email_info_penetapan' => null],
            ['id' => '3216', 'provinsi_id' => '32', 'nama' => 'KAB. BEKASI', 'email_info_penetapan' => null],
            ['id' => '3217', 'provinsi_id' => '32', 'nama' => 'KAB. BANDUNG BARAT', 'email_info_penetapan' => null],
            ['id' => '3218', 'provinsi_id' => '32', 'nama' => 'KAB. PANGANDARAN', 'email_info_penetapan' => null],
            ['id' => '3271', 'provinsi_id' => '32', 'nama' => 'KOTA BOGOR', 'email_info_penetapan' => null],
            ['id' => '3272', 'provinsi_id' => '32', 'nama' => 'KOTA SUKABUMI', 'email_info_penetapan' => null],
            ['id' => '3273', 'provinsi_id' => '32', 'nama' => 'KOTA BANDUNG', 'email_info_penetapan' => null],
            ['id' => '3274', 'provinsi_id' => '32', 'nama' => 'KOTA CIREBON', 'email_info_penetapan' => null],
            ['id' => '3275', 'provinsi_id' => '32', 'nama' => 'KOTA BEKASI', 'email_info_penetapan' => null],
            ['id' => '3276', 'provinsi_id' => '32', 'nama' => 'KOTA DEPOK', 'email_info_penetapan' => null],
            ['id' => '3277', 'provinsi_id' => '32', 'nama' => 'KOTA CIMAHI', 'email_info_penetapan' => null],
            ['id' => '3278', 'provinsi_id' => '32', 'nama' => 'KOTA TASIKMALAYA', 'email_info_penetapan' => null],
            ['id' => '3279', 'provinsi_id' => '32', 'nama' => 'KOTA BANJAR', 'email_info_penetapan' => null],
            ['id' => '3301', 'provinsi_id' => '33', 'nama' => 'KAB. CILACAP', 'email_info_penetapan' => null],
            ['id' => '3302', 'provinsi_id' => '33', 'nama' => 'KAB. BANYUMAS', 'email_info_penetapan' => null],
            ['id' => '3303', 'provinsi_id' => '33', 'nama' => 'KAB. PURBALINGGA', 'email_info_penetapan' => null],
            ['id' => '3304', 'provinsi_id' => '33', 'nama' => 'KAB. BANJARNEGARA', 'email_info_penetapan' => null],
            ['id' => '3305', 'provinsi_id' => '33', 'nama' => 'KAB. KEBUMEN', 'email_info_penetapan' => null],
            ['id' => '3306', 'provinsi_id' => '33', 'nama' => 'KAB. PURWOREJO', 'email_info_penetapan' => null],
            ['id' => '3307', 'provinsi_id' => '33', 'nama' => 'KAB. WONOSOBO', 'email_info_penetapan' => null],
            ['id' => '3308', 'provinsi_id' => '33', 'nama' => 'KAB. MAGELANG', 'email_info_penetapan' => null],
            ['id' => '3309', 'provinsi_id' => '33', 'nama' => 'KAB. BOYOLALI', 'email_info_penetapan' => null],
            ['id' => '3310', 'provinsi_id' => '33', 'nama' => 'KAB. KLATEN', 'email_info_penetapan' => null],
            ['id' => '3311', 'provinsi_id' => '33', 'nama' => 'KAB. SUKOHARJO', 'email_info_penetapan' => null],
            ['id' => '3312', 'provinsi_id' => '33', 'nama' => 'KAB. WONOGIRI', 'email_info_penetapan' => null],
            ['id' => '3313', 'provinsi_id' => '33', 'nama' => 'KAB. KARANGANYAR', 'email_info_penetapan' => null],
            ['id' => '3314', 'provinsi_id' => '33', 'nama' => 'KAB. SRAGEN', 'email_info_penetapan' => null],
            ['id' => '3315', 'provinsi_id' => '33', 'nama' => 'KAB. GROBOGAN', 'email_info_penetapan' => null],
            ['id' => '3316', 'provinsi_id' => '33', 'nama' => 'KAB. BLORA', 'email_info_penetapan' => null],
            ['id' => '3317', 'provinsi_id' => '33', 'nama' => 'KAB. REMBANG', 'email_info_penetapan' => null],
            ['id' => '3318', 'provinsi_id' => '33', 'nama' => 'KAB. PATI', 'email_info_penetapan' => null],
            ['id' => '3319', 'provinsi_id' => '33', 'nama' => 'KAB. KUDUS', 'email_info_penetapan' => null],
            ['id' => '3320', 'provinsi_id' => '33', 'nama' => 'KAB. JEPARA', 'email_info_penetapan' => null],
            ['id' => '3321', 'provinsi_id' => '33', 'nama' => 'KAB. DEMAK', 'email_info_penetapan' => null],
            ['id' => '3322', 'provinsi_id' => '33', 'nama' => 'KAB. SEMARANG', 'email_info_penetapan' => null],
            ['id' => '3323', 'provinsi_id' => '33', 'nama' => 'KAB. TEMANGGUNG', 'email_info_penetapan' => null],
            ['id' => '3324', 'provinsi_id' => '33', 'nama' => 'KAB. KENDAL', 'email_info_penetapan' => null],
            ['id' => '3325', 'provinsi_id' => '33', 'nama' => 'KAB. BATANG', 'email_info_penetapan' => null],
            ['id' => '3326', 'provinsi_id' => '33', 'nama' => 'KAB. PEKALONGAN', 'email_info_penetapan' => null],
            ['id' => '3327', 'provinsi_id' => '33', 'nama' => 'KAB. PEMALANG', 'email_info_penetapan' => null],
            ['id' => '3328', 'provinsi_id' => '33', 'nama' => 'KAB. TEGAL', 'email_info_penetapan' => null],
            ['id' => '3329', 'provinsi_id' => '33', 'nama' => 'KAB. BREBES', 'email_info_penetapan' => null],
            ['id' => '3371', 'provinsi_id' => '33', 'nama' => 'KOTA MAGELANG', 'email_info_penetapan' => null],
            ['id' => '3372', 'provinsi_id' => '33', 'nama' => 'KOTA SURAKARTA', 'email_info_penetapan' => null],
            ['id' => '3373', 'provinsi_id' => '33', 'nama' => 'KOTA SALATIGA', 'email_info_penetapan' => null],
            ['id' => '3374', 'provinsi_id' => '33', 'nama' => 'KOTA SEMARANG', 'email_info_penetapan' => null],
            ['id' => '3375', 'provinsi_id' => '33', 'nama' => 'KOTA PEKALONGAN', 'email_info_penetapan' => null],
            ['id' => '3376', 'provinsi_id' => '33', 'nama' => 'KOTA TEGAL', 'email_info_penetapan' => null],
            ['id' => '3401', 'provinsi_id' => '34', 'nama' => 'KAB. KULON PROGO', 'email_info_penetapan' => null],
            ['id' => '3402', 'provinsi_id' => '34', 'nama' => 'KAB. BANTUL', 'email_info_penetapan' => null],
            ['id' => '3403', 'provinsi_id' => '34', 'nama' => 'KAB. GUNUNGKIDUL', 'email_info_penetapan' => null],
            ['id' => '3404', 'provinsi_id' => '34', 'nama' => 'KAB. SLEMAN', 'email_info_penetapan' => null],
            ['id' => '3471', 'provinsi_id' => '34', 'nama' => 'KOTA YOGYAKARTA', 'email_info_penetapan' => null],
            ['id' => '3501', 'provinsi_id' => '35', 'nama' => 'KAB. PACITAN', 'email_info_penetapan' => null],
            ['id' => '3502', 'provinsi_id' => '35', 'nama' => 'KAB. PONOROGO', 'email_info_penetapan' => null],
            ['id' => '3503', 'provinsi_id' => '35', 'nama' => 'KAB. TRENGGALEK', 'email_info_penetapan' => null],
            ['id' => '3504', 'provinsi_id' => '35', 'nama' => 'KAB. TULUNGAGUNG', 'email_info_penetapan' => null],
            ['id' => '3505', 'provinsi_id' => '35', 'nama' => 'KAB. BLITAR', 'email_info_penetapan' => null],
            ['id' => '3506', 'provinsi_id' => '35', 'nama' => 'KAB. KEDIRI', 'email_info_penetapan' => null],
            ['id' => '3507', 'provinsi_id' => '35', 'nama' => 'KAB. MALANG', 'email_info_penetapan' => null],
            ['id' => '3508', 'provinsi_id' => '35', 'nama' => 'KAB. LUMAJANG', 'email_info_penetapan' => null],
            ['id' => '3509', 'provinsi_id' => '35', 'nama' => 'KAB. JEMBER', 'email_info_penetapan' => null],
            ['id' => '3510', 'provinsi_id' => '35', 'nama' => 'KAB. BANYUWANGI', 'email_info_penetapan' => null],
            ['id' => '3511', 'provinsi_id' => '35', 'nama' => 'KAB. BONDOWOSO', 'email_info_penetapan' => null],
            ['id' => '3512', 'provinsi_id' => '35', 'nama' => 'KAB. SITUBONDO', 'email_info_penetapan' => null],
            ['id' => '3513', 'provinsi_id' => '35', 'nama' => 'KAB. PROBOLINGGO', 'email_info_penetapan' => null],
            ['id' => '3514', 'provinsi_id' => '35', 'nama' => 'KAB. PASURUAN', 'email_info_penetapan' => null],
            ['id' => '3515', 'provinsi_id' => '35', 'nama' => 'KAB. SIDOARJO', 'email_info_penetapan' => null],
            ['id' => '3516', 'provinsi_id' => '35', 'nama' => 'KAB. MOJOKERTO', 'email_info_penetapan' => null],
            ['id' => '3517', 'provinsi_id' => '35', 'nama' => 'KAB. JOMBANG', 'email_info_penetapan' => null],
            ['id' => '3518', 'provinsi_id' => '35', 'nama' => 'KAB. NGANJUK', 'email_info_penetapan' => null],
            ['id' => '3519', 'provinsi_id' => '35', 'nama' => 'KAB. MADIUN', 'email_info_penetapan' => null],
            ['id' => '3520', 'provinsi_id' => '35', 'nama' => 'KAB. MAGETAN', 'email_info_penetapan' => null],
            ['id' => '3521', 'provinsi_id' => '35', 'nama' => 'KAB. NGAWI', 'email_info_penetapan' => null],
            ['id' => '3522', 'provinsi_id' => '35', 'nama' => 'KAB. BOJONEGORO', 'email_info_penetapan' => null],
            ['id' => '3523', 'provinsi_id' => '35', 'nama' => 'KAB. TUBAN', 'email_info_penetapan' => null],
            ['id' => '3524', 'provinsi_id' => '35', 'nama' => 'KAB. LAMONGAN', 'email_info_penetapan' => null],
            ['id' => '3525', 'provinsi_id' => '35', 'nama' => 'KAB. GRESIK', 'email_info_penetapan' => null],
            ['id' => '3526', 'provinsi_id' => '35', 'nama' => 'KAB. BANGKALAN', 'email_info_penetapan' => null],
            ['id' => '3527', 'provinsi_id' => '35', 'nama' => 'KAB. SAMPANG', 'email_info_penetapan' => null],
            ['id' => '3528', 'provinsi_id' => '35', 'nama' => 'KAB. PAMEKASAN', 'email_info_penetapan' => null],
            ['id' => '3529', 'provinsi_id' => '35', 'nama' => 'KAB. SUMENEP', 'email_info_penetapan' => null],
            ['id' => '3571', 'provinsi_id' => '35', 'nama' => 'KOTA KEDIRI', 'email_info_penetapan' => null],
            ['id' => '3572', 'provinsi_id' => '35', 'nama' => 'KOTA BLITAR', 'email_info_penetapan' => null],
            ['id' => '3573', 'provinsi_id' => '35', 'nama' => 'KOTA MALANG', 'email_info_penetapan' => null],
            ['id' => '3574', 'provinsi_id' => '35', 'nama' => 'KOTA PROBOLINGGO', 'email_info_penetapan' => null],
            ['id' => '3575', 'provinsi_id' => '35', 'nama' => 'KOTA PASURUAN', 'email_info_penetapan' => null],
            ['id' => '3576', 'provinsi_id' => '35', 'nama' => 'KOTA MOJOKERTO', 'email_info_penetapan' => null],
            ['id' => '3577', 'provinsi_id' => '35', 'nama' => 'KOTA MADIUN', 'email_info_penetapan' => null],
            ['id' => '3578', 'provinsi_id' => '35', 'nama' => 'KOTA SURABAYA', 'email_info_penetapan' => null],
            ['id' => '3579', 'provinsi_id' => '35', 'nama' => 'KOTA BATU', 'email_info_penetapan' => null],
            ['id' => '3601', 'provinsi_id' => '36', 'nama' => 'KAB. PANDEGLANG', 'email_info_penetapan' => null],
            ['id' => '3602', 'provinsi_id' => '36', 'nama' => 'KAB. LEBAK', 'email_info_penetapan' => null],
            ['id' => '3603', 'provinsi_id' => '36', 'nama' => 'KAB. TANGERANG', 'email_info_penetapan' => null],
            ['id' => '3604', 'provinsi_id' => '36', 'nama' => 'KAB. SERANG', 'email_info_penetapan' => null],
            ['id' => '3671', 'provinsi_id' => '36', 'nama' => 'KOTA TANGERANG', 'email_info_penetapan' => null],
            ['id' => '3672', 'provinsi_id' => '36', 'nama' => 'KOTA CILEGON', 'email_info_penetapan' => null],
            ['id' => '3673', 'provinsi_id' => '36', 'nama' => 'KOTA SERANG', 'email_info_penetapan' => null],
            ['id' => '3674', 'provinsi_id' => '36', 'nama' => 'KOTA TANGERANG SELATAN', 'email_info_penetapan' => null],
            ['id' => '5101', 'provinsi_id' => '51', 'nama' => 'KAB. JEMBRANA', 'email_info_penetapan' => null],
            ['id' => '5102', 'provinsi_id' => '51', 'nama' => 'KAB. TABANAN', 'email_info_penetapan' => null],
            ['id' => '5103', 'provinsi_id' => '51', 'nama' => 'KAB. BADUNG', 'email_info_penetapan' => null],
            ['id' => '5104', 'provinsi_id' => '51', 'nama' => 'KAB. GIANYAR', 'email_info_penetapan' => null],
            ['id' => '5105', 'provinsi_id' => '51', 'nama' => 'KAB. KLUNGKUNG', 'email_info_penetapan' => null],
            ['id' => '5106', 'provinsi_id' => '51', 'nama' => 'KAB. BANGLI', 'email_info_penetapan' => null],
            ['id' => '5107', 'provinsi_id' => '51', 'nama' => 'KAB. KARANGASEM', 'email_info_penetapan' => null],
            ['id' => '5108', 'provinsi_id' => '51', 'nama' => 'KAB. BULELENG', 'email_info_penetapan' => null],
            ['id' => '5171', 'provinsi_id' => '51', 'nama' => 'KOTA DENPASAR', 'email_info_penetapan' => null],
            ['id' => '5201', 'provinsi_id' => '52', 'nama' => 'KAB. LOMBOK BARAT', 'email_info_penetapan' => null],
            ['id' => '5202', 'provinsi_id' => '52', 'nama' => 'KAB. LOMBOK TENGAH', 'email_info_penetapan' => null],
            ['id' => '5203', 'provinsi_id' => '52', 'nama' => 'KAB. LOMBOK TIMUR', 'email_info_penetapan' => null],
            ['id' => '5204', 'provinsi_id' => '52', 'nama' => 'KAB. SUMBAWA', 'email_info_penetapan' => null],
            ['id' => '5205', 'provinsi_id' => '52', 'nama' => 'KAB. DOMPU', 'email_info_penetapan' => null],
            ['id' => '5206', 'provinsi_id' => '52', 'nama' => 'KAB. BIMA', 'email_info_penetapan' => null],
            ['id' => '5207', 'provinsi_id' => '52', 'nama' => 'KAB. SUMBAWA BARAT', 'email_info_penetapan' => null],
            ['id' => '5208', 'provinsi_id' => '52', 'nama' => 'KAB. LOMBOK UTARA', 'email_info_penetapan' => null],
            ['id' => '5271', 'provinsi_id' => '52', 'nama' => 'KOTA MATARAM', 'email_info_penetapan' => null],
            ['id' => '5272', 'provinsi_id' => '52', 'nama' => 'KOTA BIMA', 'email_info_penetapan' => null],
            ['id' => '5301', 'provinsi_id' => '53', 'nama' => 'KAB. KUPANG', 'email_info_penetapan' => null],
            ['id' => '5302', 'provinsi_id' => '53', 'nama' => 'KAB TIMOR TENGAH SELATAN', 'email_info_penetapan' => null],
            ['id' => '5303', 'provinsi_id' => '53', 'nama' => 'KAB. TIMOR TENGAH UTARA', 'email_info_penetapan' => null],
            ['id' => '5304', 'provinsi_id' => '53', 'nama' => 'KAB. BELU', 'email_info_penetapan' => null],
            ['id' => '5305', 'provinsi_id' => '53', 'nama' => 'KAB. ALOR', 'email_info_penetapan' => null],
            ['id' => '5306', 'provinsi_id' => '53', 'nama' => 'KAB. FLORES TIMUR', 'email_info_penetapan' => null],
            ['id' => '5307', 'provinsi_id' => '53', 'nama' => 'KAB. SIKKA', 'email_info_penetapan' => null],
            ['id' => '5308', 'provinsi_id' => '53', 'nama' => 'KAB. ENDE', 'email_info_penetapan' => null],
            ['id' => '5309', 'provinsi_id' => '53', 'nama' => 'KAB. NGADA', 'email_info_penetapan' => null],
            ['id' => '5310', 'provinsi_id' => '53', 'nama' => 'KAB. MANGGARAI', 'email_info_penetapan' => null],
            ['id' => '5311', 'provinsi_id' => '53', 'nama' => 'KAB. SUMBA TIMUR', 'email_info_penetapan' => null],
            ['id' => '5312', 'provinsi_id' => '53', 'nama' => 'KAB. SUMBA BARAT', 'email_info_penetapan' => null],
            ['id' => '5313', 'provinsi_id' => '53', 'nama' => 'KAB. LEMBATA', 'email_info_penetapan' => null],
            ['id' => '5314', 'provinsi_id' => '53', 'nama' => 'KAB. ROTE NDAO', 'email_info_penetapan' => null],
            ['id' => '5315', 'provinsi_id' => '53', 'nama' => 'KAB. MANGGARAI BARAT', 'email_info_penetapan' => null],
            ['id' => '5316', 'provinsi_id' => '53', 'nama' => 'KAB. NAGEKEO', 'email_info_penetapan' => null],
            ['id' => '5317', 'provinsi_id' => '53', 'nama' => 'KAB. SUMBA TENGAH', 'email_info_penetapan' => null],
            ['id' => '5318', 'provinsi_id' => '53', 'nama' => 'KAB. SUMBA BARAT DAYA', 'email_info_penetapan' => null],
            ['id' => '5319', 'provinsi_id' => '53', 'nama' => 'KAB. MANGGARAI TIMUR', 'email_info_penetapan' => null],
            ['id' => '5320', 'provinsi_id' => '53', 'nama' => 'KAB. SABU RAIJUA', 'email_info_penetapan' => null],
            ['id' => '5321', 'provinsi_id' => '53', 'nama' => 'KAB. MALAKA', 'email_info_penetapan' => null],
            ['id' => '5371', 'provinsi_id' => '53', 'nama' => 'KOTA KUPANG', 'email_info_penetapan' => null],
            ['id' => '6101', 'provinsi_id' => '61', 'nama' => 'KAB. SAMBAS', 'email_info_penetapan' => null],
            ['id' => '6102', 'provinsi_id' => '61', 'nama' => 'KAB. MEMPAWAH', 'email_info_penetapan' => null],
            ['id' => '6103', 'provinsi_id' => '61', 'nama' => 'KAB. SANGGAU', 'email_info_penetapan' => null],
            ['id' => '6104', 'provinsi_id' => '61', 'nama' => 'KAB. KETAPANG', 'email_info_penetapan' => null],
            ['id' => '6105', 'provinsi_id' => '61', 'nama' => 'KAB. SINTANG', 'email_info_penetapan' => null],
            ['id' => '6106', 'provinsi_id' => '61', 'nama' => 'KAB. KAPUAS HULU', 'email_info_penetapan' => null],
            ['id' => '6107', 'provinsi_id' => '61', 'nama' => 'KAB. BENGKAYANG', 'email_info_penetapan' => null],
            ['id' => '6108', 'provinsi_id' => '61', 'nama' => 'KAB. LANDAK', 'email_info_penetapan' => null],
            ['id' => '6109', 'provinsi_id' => '61', 'nama' => 'KAB. SEKADAU', 'email_info_penetapan' => null],
            ['id' => '6110', 'provinsi_id' => '61', 'nama' => 'KAB. MELAWI', 'email_info_penetapan' => null],
            ['id' => '6111', 'provinsi_id' => '61', 'nama' => 'KAB. KAYONG UTARA', 'email_info_penetapan' => null],
            ['id' => '6112', 'provinsi_id' => '61', 'nama' => 'KAB. KUBU RAYA', 'email_info_penetapan' => null],
            ['id' => '6171', 'provinsi_id' => '61', 'nama' => 'KOTA PONTIANAK', 'email_info_penetapan' => null],
            ['id' => '6172', 'provinsi_id' => '61', 'nama' => 'KOTA SINGKAWANG', 'email_info_penetapan' => null],
            ['id' => '6201', 'provinsi_id' => '62', 'nama' => 'KAB. KOTAWARINGIN BARAT', 'email_info_penetapan' => null],
            ['id' => '6202', 'provinsi_id' => '62', 'nama' => 'KAB. KOTAWARINGIN TIMUR', 'email_info_penetapan' => null],
            ['id' => '6203', 'provinsi_id' => '62', 'nama' => 'KAB. KAPUAS', 'email_info_penetapan' => null],
            ['id' => '6204', 'provinsi_id' => '62', 'nama' => 'KAB. BARITO SELATAN', 'email_info_penetapan' => null],
            ['id' => '6205', 'provinsi_id' => '62', 'nama' => 'KAB. BARITO UTARA', 'email_info_penetapan' => null],
            ['id' => '6206', 'provinsi_id' => '62', 'nama' => 'KAB. KATINGAN', 'email_info_penetapan' => null],
            ['id' => '6207', 'provinsi_id' => '62', 'nama' => 'KAB. SERUYAN', 'email_info_penetapan' => null],
            ['id' => '6208', 'provinsi_id' => '62', 'nama' => 'KAB. SUKAMARA', 'email_info_penetapan' => null],
            ['id' => '6209', 'provinsi_id' => '62', 'nama' => 'KAB. LAMANDAU', 'email_info_penetapan' => null],
            ['id' => '6210', 'provinsi_id' => '62', 'nama' => 'KAB. GUNUNG MAS', 'email_info_penetapan' => null],
            ['id' => '6211', 'provinsi_id' => '62', 'nama' => 'KAB. PULANG PISAU', 'email_info_penetapan' => null],
            ['id' => '6212', 'provinsi_id' => '62', 'nama' => 'KAB. MURUNG RAYA', 'email_info_penetapan' => null],
            ['id' => '6213', 'provinsi_id' => '62', 'nama' => 'KAB. BARITO TIMUR', 'email_info_penetapan' => null],
            ['id' => '6271', 'provinsi_id' => '62', 'nama' => 'KOTA PALANGKARAYA', 'email_info_penetapan' => null],
            ['id' => '6301', 'provinsi_id' => '63', 'nama' => 'KAB. TANAH LAUT', 'email_info_penetapan' => null],
            ['id' => '6302', 'provinsi_id' => '63', 'nama' => 'KAB. KOTABARU', 'email_info_penetapan' => null],
            ['id' => '6303', 'provinsi_id' => '63', 'nama' => 'KAB. BANJAR', 'email_info_penetapan' => null],
            ['id' => '6304', 'provinsi_id' => '63', 'nama' => 'KAB. BARITO KUALA', 'email_info_penetapan' => null],
            ['id' => '6305', 'provinsi_id' => '63', 'nama' => 'KAB. TAPIN', 'email_info_penetapan' => null],
            ['id' => '6306', 'provinsi_id' => '63', 'nama' => 'KAB. HULU SUNGAI SELATAN', 'email_info_penetapan' => null],
            ['id' => '6307', 'provinsi_id' => '63', 'nama' => 'KAB. HULU SUNGAI TENGAH', 'email_info_penetapan' => null],
            ['id' => '6308', 'provinsi_id' => '63', 'nama' => 'KAB. HULU SUNGAI UTARA', 'email_info_penetapan' => null],
            ['id' => '6309', 'provinsi_id' => '63', 'nama' => 'KAB. TABALONG', 'email_info_penetapan' => null],
            ['id' => '6310', 'provinsi_id' => '63', 'nama' => 'KAB. TANAH BUMBU', 'email_info_penetapan' => null],
            ['id' => '6311', 'provinsi_id' => '63', 'nama' => 'KAB. BALANGAN', 'email_info_penetapan' => null],
            ['id' => '6371', 'provinsi_id' => '63', 'nama' => 'KOTA BANJARMASIN', 'email_info_penetapan' => null],
            ['id' => '6372', 'provinsi_id' => '63', 'nama' => 'KOTA BANJARBARU', 'email_info_penetapan' => null],
            ['id' => '6401', 'provinsi_id' => '64', 'nama' => 'KAB. PASER', 'email_info_penetapan' => null],
            ['id' => '6402', 'provinsi_id' => '64', 'nama' => 'KAB. KUTAI KARTANEGARA', 'email_info_penetapan' => null],
            ['id' => '6403', 'provinsi_id' => '64', 'nama' => 'KAB. BERAU', 'email_info_penetapan' => null],
            ['id' => '6407', 'provinsi_id' => '64', 'nama' => 'KAB. KUTAI BARAT', 'email_info_penetapan' => null],
            ['id' => '6408', 'provinsi_id' => '64', 'nama' => 'KAB. KUTAI TIMUR', 'email_info_penetapan' => null],
            ['id' => '6409', 'provinsi_id' => '64', 'nama' => 'KAB. PENAJAM PASER UTARA', 'email_info_penetapan' => null],
            ['id' => '6411', 'provinsi_id' => '64', 'nama' => 'KAB. MAHAKAM ULU', 'email_info_penetapan' => null],
            ['id' => '6471', 'provinsi_id' => '64', 'nama' => 'KOTA BALIKPAPAN', 'email_info_penetapan' => null],
            ['id' => '6472', 'provinsi_id' => '64', 'nama' => 'KOTA SAMARINDA', 'email_info_penetapan' => null],
            ['id' => '6474', 'provinsi_id' => '64', 'nama' => 'KOTA BONTANG', 'email_info_penetapan' => null],
            ['id' => '6501', 'provinsi_id' => '65', 'nama' => 'KAB. BULUNGAN', 'email_info_penetapan' => null],
            ['id' => '6502', 'provinsi_id' => '65', 'nama' => 'KAB. MALINAU', 'email_info_penetapan' => null],
            ['id' => '6503', 'provinsi_id' => '65', 'nama' => 'KAB. NUNUKAN', 'email_info_penetapan' => null],
            ['id' => '6504', 'provinsi_id' => '65', 'nama' => 'KAB. TANA TIDUNG', 'email_info_penetapan' => null],
            ['id' => '6571', 'provinsi_id' => '65', 'nama' => 'KOTA TARAKAN', 'email_info_penetapan' => null],
            ['id' => '7101', 'provinsi_id' => '71', 'nama' => 'KAB. BOLAANG MONGONDOW', 'email_info_penetapan' => null],
            ['id' => '7102', 'provinsi_id' => '71', 'nama' => 'KAB. MINAHASA', 'email_info_penetapan' => null],
            ['id' => '7103', 'provinsi_id' => '71', 'nama' => 'KAB. KEPULAUAN SANGIHE', 'email_info_penetapan' => null],
            ['id' => '7104', 'provinsi_id' => '71', 'nama' => 'KAB. KEPULAUAN TALAUD', 'email_info_penetapan' => null],
            ['id' => '7105', 'provinsi_id' => '71', 'nama' => 'KAB. MINAHASA SELATAN', 'email_info_penetapan' => null],
            ['id' => '7106', 'provinsi_id' => '71', 'nama' => 'KAB. MINAHASA UTARA', 'email_info_penetapan' => null],
            ['id' => '7107', 'provinsi_id' => '71', 'nama' => 'KAB. MINAHASA TENGGARA', 'email_info_penetapan' => null],
            ['id' => '7108', 'provinsi_id' => '71', 'nama' => 'KAB. BOLAANG MONGONDOW UTARA', 'email_info_penetapan' => null],
            ['id' => '7109', 'provinsi_id' => '71', 'nama' => 'KAB. KEP. SIAU TAGULANDANG BIARO', 'email_info_penetapan' => null],
            ['id' => '7110', 'provinsi_id' => '71', 'nama' => 'KAB. BOLAANG MONGONDOW TIMUR', 'email_info_penetapan' => null],
            ['id' => '7111', 'provinsi_id' => '71', 'nama' => 'KAB. BOLAANG MONGONDOW SELATAN', 'email_info_penetapan' => null],
            ['id' => '7171', 'provinsi_id' => '71', 'nama' => 'KOTA MANADO', 'email_info_penetapan' => null],
            ['id' => '7172', 'provinsi_id' => '71', 'nama' => 'KOTA BITUNG', 'email_info_penetapan' => null],
            ['id' => '7173', 'provinsi_id' => '71', 'nama' => 'KOTA TOMOHON', 'email_info_penetapan' => null],
            ['id' => '7174', 'provinsi_id' => '71', 'nama' => 'KOTA KOTAMOBAGU', 'email_info_penetapan' => null],
            ['id' => '7201', 'provinsi_id' => '72', 'nama' => 'KAB. BANGGAI', 'email_info_penetapan' => null],
            ['id' => '7202', 'provinsi_id' => '72', 'nama' => 'KAB. POSO', 'email_info_penetapan' => null],
            ['id' => '7203', 'provinsi_id' => '72', 'nama' => 'KAB. DONGGALA', 'email_info_penetapan' => null],
            ['id' => '7204', 'provinsi_id' => '72', 'nama' => 'KAB. TOLI TOLI', 'email_info_penetapan' => null],
            ['id' => '7205', 'provinsi_id' => '72', 'nama' => 'KAB. BUOL', 'email_info_penetapan' => null],
            ['id' => '7206', 'provinsi_id' => '72', 'nama' => 'KAB. MOROWALI', 'email_info_penetapan' => null],
            ['id' => '7207', 'provinsi_id' => '72', 'nama' => 'KAB. BANGGAI KEPULAUAN', 'email_info_penetapan' => null],
            ['id' => '7208', 'provinsi_id' => '72', 'nama' => 'KAB. PARIGI MOUTONG', 'email_info_penetapan' => null],
            ['id' => '7209', 'provinsi_id' => '72', 'nama' => 'KAB. TOJO UNA UNA', 'email_info_penetapan' => null],
            ['id' => '7210', 'provinsi_id' => '72', 'nama' => 'KAB. SIGI', 'email_info_penetapan' => null],
            ['id' => '7211', 'provinsi_id' => '72', 'nama' => 'KAB. BANGGAI LAUT', 'email_info_penetapan' => null],
            ['id' => '7212', 'provinsi_id' => '72', 'nama' => 'KAB. MOROWALI UTARA', 'email_info_penetapan' => null],
            ['id' => '7271', 'provinsi_id' => '72', 'nama' => 'KOTA PALU', 'email_info_penetapan' => null],
            ['id' => '7301', 'provinsi_id' => '73', 'nama' => 'KAB. KEPULAUAN SELAYAR', 'email_info_penetapan' => null],
            ['id' => '7302', 'provinsi_id' => '73', 'nama' => 'KAB. BULUKUMBA', 'email_info_penetapan' => null],
            ['id' => '7303', 'provinsi_id' => '73', 'nama' => 'KAB. BANTAENG', 'email_info_penetapan' => null],
            ['id' => '7304', 'provinsi_id' => '73', 'nama' => 'KAB. JENEPONTO', 'email_info_penetapan' => null],
            ['id' => '7305', 'provinsi_id' => '73', 'nama' => 'KAB. TAKALAR', 'email_info_penetapan' => null],
            ['id' => '7306', 'provinsi_id' => '73', 'nama' => 'KAB. GOWA', 'email_info_penetapan' => null],
            ['id' => '7307', 'provinsi_id' => '73', 'nama' => 'KAB. SINJAI', 'email_info_penetapan' => null],
            ['id' => '7308', 'provinsi_id' => '73', 'nama' => 'KAB. BONE', 'email_info_penetapan' => null],
            ['id' => '7309', 'provinsi_id' => '73', 'nama' => 'KAB. MAROS', 'email_info_penetapan' => null],
            ['id' => '7310', 'provinsi_id' => '73', 'nama' => 'KAB. PANGKAJENE KEPULAUAN', 'email_info_penetapan' => null],
            ['id' => '7311', 'provinsi_id' => '73', 'nama' => 'KAB. BARRU', 'email_info_penetapan' => null],
            ['id' => '7312', 'provinsi_id' => '73', 'nama' => 'KAB. SOPPENG', 'email_info_penetapan' => null],
            ['id' => '7313', 'provinsi_id' => '73', 'nama' => 'KAB. WAJO', 'email_info_penetapan' => null],
            ['id' => '7314', 'provinsi_id' => '73', 'nama' => 'KAB. SIDENRENG RAPPANG', 'email_info_penetapan' => null],
            ['id' => '7315', 'provinsi_id' => '73', 'nama' => 'KAB. PINRANG', 'email_info_penetapan' => null],
            ['id' => '7316', 'provinsi_id' => '73', 'nama' => 'KAB. ENREKANG', 'email_info_penetapan' => null],
            ['id' => '7317', 'provinsi_id' => '73', 'nama' => 'KAB. LUWU', 'email_info_penetapan' => null],
            ['id' => '7318', 'provinsi_id' => '73', 'nama' => 'KAB. TANA TORAJA', 'email_info_penetapan' => null],
            ['id' => '7322', 'provinsi_id' => '73', 'nama' => 'KAB. LUWU UTARA', 'email_info_penetapan' => null],
            ['id' => '7324', 'provinsi_id' => '73', 'nama' => 'KAB. LUWU TIMUR', 'email_info_penetapan' => null],
            ['id' => '7326', 'provinsi_id' => '73', 'nama' => 'KAB. TORAJA UTARA', 'email_info_penetapan' => null],
            ['id' => '7371', 'provinsi_id' => '73', 'nama' => 'KOTA MAKASSAR', 'email_info_penetapan' => null],
            ['id' => '7372', 'provinsi_id' => '73', 'nama' => 'KOTA PARE PARE', 'email_info_penetapan' => null],
            ['id' => '7373', 'provinsi_id' => '73', 'nama' => 'KOTA PALOPO', 'email_info_penetapan' => null],
            ['id' => '7401', 'provinsi_id' => '74', 'nama' => 'KAB. KOLAKA', 'email_info_penetapan' => null],
            ['id' => '7402', 'provinsi_id' => '74', 'nama' => 'KAB. KONAWE', 'email_info_penetapan' => null],
            ['id' => '7403', 'provinsi_id' => '74', 'nama' => 'KAB. MUNA', 'email_info_penetapan' => null],
            ['id' => '7404', 'provinsi_id' => '74', 'nama' => 'KAB. BUTON', 'email_info_penetapan' => null],
            ['id' => '7405', 'provinsi_id' => '74', 'nama' => 'KAB. KONAWE SELATAN', 'email_info_penetapan' => null],
            ['id' => '7406', 'provinsi_id' => '74', 'nama' => 'KAB. BOMBANA', 'email_info_penetapan' => null],
            ['id' => '7407', 'provinsi_id' => '74', 'nama' => 'KAB. WAKATOBI', 'email_info_penetapan' => null],
            ['id' => '7408', 'provinsi_id' => '74', 'nama' => 'KAB. KOLAKA UTARA', 'email_info_penetapan' => null],
            ['id' => '7409', 'provinsi_id' => '74', 'nama' => 'KAB. KONAWE UTARA', 'email_info_penetapan' => null],
            ['id' => '7410', 'provinsi_id' => '74', 'nama' => 'KAB. BUTON UTARA', 'email_info_penetapan' => null],
            ['id' => '7411', 'provinsi_id' => '74', 'nama' => 'KAB. KOLAKA TIMUR', 'email_info_penetapan' => null],
            ['id' => '7412', 'provinsi_id' => '74', 'nama' => 'KAB. KONAWE KEPULAUAN', 'email_info_penetapan' => null],
            ['id' => '7413', 'provinsi_id' => '74', 'nama' => 'KAB. MUNA BARAT', 'email_info_penetapan' => null],
            ['id' => '7414', 'provinsi_id' => '74', 'nama' => 'KAB. BUTON TENGAH', 'email_info_penetapan' => null],
            ['id' => '7415', 'provinsi_id' => '74', 'nama' => 'KAB. BUTON SELATAN', 'email_info_penetapan' => null],
            ['id' => '7471', 'provinsi_id' => '74', 'nama' => 'KOTA KENDARI', 'email_info_penetapan' => null],
            ['id' => '7472', 'provinsi_id' => '74', 'nama' => 'KOTA BAU BAU', 'email_info_penetapan' => null],
            ['id' => '7501', 'provinsi_id' => '75', 'nama' => 'KAB. GORONTALO', 'email_info_penetapan' => null],
            ['id' => '7502', 'provinsi_id' => '75', 'nama' => 'KAB. BOALEMO', 'email_info_penetapan' => null],
            ['id' => '7503', 'provinsi_id' => '75', 'nama' => 'KAB. BONE BOLANGO', 'email_info_penetapan' => null],
            ['id' => '7504', 'provinsi_id' => '75', 'nama' => 'KAB. PAHUWATO', 'email_info_penetapan' => null],
            ['id' => '7505', 'provinsi_id' => '75', 'nama' => 'KAB. GORONTALO UTARA', 'email_info_penetapan' => null],
            ['id' => '7571', 'provinsi_id' => '75', 'nama' => 'KOTA GORONTALO', 'email_info_penetapan' => null],
            ['id' => '7601', 'provinsi_id' => '76', 'nama' => 'KAB. PASANGKAYU', 'email_info_penetapan' => null],
            ['id' => '7602', 'provinsi_id' => '76', 'nama' => 'KAB. MAMUJU', 'email_info_penetapan' => null],
            ['id' => '7603', 'provinsi_id' => '76', 'nama' => 'KAB. MAMASA', 'email_info_penetapan' => null],
            ['id' => '7604', 'provinsi_id' => '76', 'nama' => 'KAB. POLEWALI MANDAR', 'email_info_penetapan' => null],
            ['id' => '7605', 'provinsi_id' => '76', 'nama' => 'KAB. MAJENE', 'email_info_penetapan' => null],
            ['id' => '7606', 'provinsi_id' => '76', 'nama' => 'KAB. MAMUJU TENGAH', 'email_info_penetapan' => null],
            ['id' => '8101', 'provinsi_id' => '81', 'nama' => 'KAB. MALUKU TENGAH', 'email_info_penetapan' => null],
            ['id' => '8102', 'provinsi_id' => '81', 'nama' => 'KAB. MALUKU TENGGARA', 'email_info_penetapan' => null],
            ['id' => '8103', 'provinsi_id' => '81', 'nama' => 'KAB. KEPULAUAN TANIMBAR', 'email_info_penetapan' => null],
            ['id' => '8104', 'provinsi_id' => '81', 'nama' => 'KAB. BURU', 'email_info_penetapan' => null],
            ['id' => '8105', 'provinsi_id' => '81', 'nama' => 'KAB. SERAM BAGIAN TIMUR', 'email_info_penetapan' => null],
            ['id' => '8106', 'provinsi_id' => '81', 'nama' => 'KAB. SERAM BAGIAN BARAT', 'email_info_penetapan' => null],
            ['id' => '8107', 'provinsi_id' => '81', 'nama' => 'KAB. KEPULAUAN ARU', 'email_info_penetapan' => null],
            ['id' => '8108', 'provinsi_id' => '81', 'nama' => 'KAB. MALUKU BARAT DAYA', 'email_info_penetapan' => null],
            ['id' => '8109', 'provinsi_id' => '81', 'nama' => 'KAB. BURU SELATAN', 'email_info_penetapan' => null],
            ['id' => '8171', 'provinsi_id' => '81', 'nama' => 'KOTA AMBON', 'email_info_penetapan' => null],
            ['id' => '8172', 'provinsi_id' => '81', 'nama' => 'KOTA TUAL', 'email_info_penetapan' => null],
            ['id' => '8201', 'provinsi_id' => '82', 'nama' => 'KAB. HALMAHERA BARAT', 'email_info_penetapan' => null],
            ['id' => '8202', 'provinsi_id' => '82', 'nama' => 'KAB. HALMAHERA TENGAH', 'email_info_penetapan' => null],
            ['id' => '8203', 'provinsi_id' => '82', 'nama' => 'KAB. HALMAHERA UTARA', 'email_info_penetapan' => null],
            ['id' => '8204', 'provinsi_id' => '82', 'nama' => 'KAB. HALMAHERA SELATAN', 'email_info_penetapan' => null],
            ['id' => '8205', 'provinsi_id' => '82', 'nama' => 'KAB. KEPULAUAN SULA', 'email_info_penetapan' => null],
            ['id' => '8206', 'provinsi_id' => '82', 'nama' => 'KAB. HALMAHERA TIMUR', 'email_info_penetapan' => null],
            ['id' => '8207', 'provinsi_id' => '82', 'nama' => 'KAB. PULAU MOROTAI', 'email_info_penetapan' => null],
            ['id' => '8208', 'provinsi_id' => '82', 'nama' => 'KAB. PULAU TALIABU', 'email_info_penetapan' => null],
            ['id' => '8271', 'provinsi_id' => '82', 'nama' => 'KOTA TERNATE', 'email_info_penetapan' => null],
            ['id' => '8272', 'provinsi_id' => '82', 'nama' => 'KOTA TIDORE KEPULAUAN', 'email_info_penetapan' => null],
            ['id' => '9101', 'provinsi_id' => '91', 'nama' => 'KAB. MERAUKE', 'email_info_penetapan' => null],
            ['id' => '9102', 'provinsi_id' => '91', 'nama' => 'KAB. JAYAWIJAYA', 'email_info_penetapan' => null],
            ['id' => '9103', 'provinsi_id' => '91', 'nama' => 'KAB. JAYAPURA', 'email_info_penetapan' => null],
            ['id' => '9104', 'provinsi_id' => '91', 'nama' => 'KAB. NABIRE', 'email_info_penetapan' => null],
            ['id' => '9105', 'provinsi_id' => '91', 'nama' => 'KAB. KEPULAUAN YAPEN', 'email_info_penetapan' => null],
            ['id' => '9106', 'provinsi_id' => '91', 'nama' => 'KAB. BIAK NUMFOR', 'email_info_penetapan' => null],
            ['id' => '9107', 'provinsi_id' => '91', 'nama' => 'KAB. PUNCAK JAYA', 'email_info_penetapan' => null],
            ['id' => '9108', 'provinsi_id' => '91', 'nama' => 'KAB. PANIAI', 'email_info_penetapan' => null],
            ['id' => '9109', 'provinsi_id' => '91', 'nama' => 'KAB. MIMIKA', 'email_info_penetapan' => null],
            ['id' => '9110', 'provinsi_id' => '91', 'nama' => 'KAB. SARMI', 'email_info_penetapan' => null],
            ['id' => '9111', 'provinsi_id' => '91', 'nama' => 'KAB. KEEROM', 'email_info_penetapan' => null],
            ['id' => '9112', 'provinsi_id' => '91', 'nama' => 'KAB PEGUNUNGAN BINTANG', 'email_info_penetapan' => null],
            ['id' => '9113', 'provinsi_id' => '91', 'nama' => 'KAB. YAHUKIMO', 'email_info_penetapan' => null],
            ['id' => '9114', 'provinsi_id' => '91', 'nama' => 'KAB. TOLIKARA', 'email_info_penetapan' => null],
            ['id' => '9115', 'provinsi_id' => '91', 'nama' => 'KAB. WAROPEN', 'email_info_penetapan' => null],
            ['id' => '9116', 'provinsi_id' => '91', 'nama' => 'KAB. BOVEN DIGOEL', 'email_info_penetapan' => null],
            ['id' => '9117', 'provinsi_id' => '91', 'nama' => 'KAB. MAPPI', 'email_info_penetapan' => null],
            ['id' => '9118', 'provinsi_id' => '91', 'nama' => 'KAB. ASMAT', 'email_info_penetapan' => null],
            ['id' => '9119', 'provinsi_id' => '91', 'nama' => 'KAB. SUPIORI', 'email_info_penetapan' => null],
            ['id' => '9120', 'provinsi_id' => '91', 'nama' => 'KAB. MAMBERAMO RAYA', 'email_info_penetapan' => null],
            ['id' => '9121', 'provinsi_id' => '91', 'nama' => 'KAB. MAMBERAMO TENGAH', 'email_info_penetapan' => null],
            ['id' => '9122', 'provinsi_id' => '91', 'nama' => 'KAB. YALIMO', 'email_info_penetapan' => null],
            ['id' => '9123', 'provinsi_id' => '91', 'nama' => 'KAB. LANNY JAYA', 'email_info_penetapan' => null],
            ['id' => '9124', 'provinsi_id' => '91', 'nama' => 'KAB. NDUGA', 'email_info_penetapan' => null],
            ['id' => '9125', 'provinsi_id' => '91', 'nama' => 'KAB. PUNCAK', 'email_info_penetapan' => null],
            ['id' => '9126', 'provinsi_id' => '91', 'nama' => 'KAB. DOGIYAI', 'email_info_penetapan' => null],
            ['id' => '9127', 'provinsi_id' => '91', 'nama' => 'KAB. INTAN JAYA', 'email_info_penetapan' => null],
            ['id' => '9128', 'provinsi_id' => '91', 'nama' => 'KAB. DEIYAI', 'email_info_penetapan' => null],
            ['id' => '9171', 'provinsi_id' => '91', 'nama' => 'KOTA JAYAPURA', 'email_info_penetapan' => null],
            ['id' => '9201', 'provinsi_id' => '92', 'nama' => 'KAB. SORONG', 'email_info_penetapan' => null],
            ['id' => '9202', 'provinsi_id' => '92', 'nama' => 'KAB. MANOKWARI', 'email_info_penetapan' => null],
            ['id' => '9203', 'provinsi_id' => '92', 'nama' => 'KAB. FAK FAK', 'email_info_penetapan' => null],
            ['id' => '9204', 'provinsi_id' => '92', 'nama' => 'KAB. SORONG SELATAN', 'email_info_penetapan' => null],
            ['id' => '9205', 'provinsi_id' => '92', 'nama' => 'KAB. RAJA AMPAT', 'email_info_penetapan' => null],
            ['id' => '9206', 'provinsi_id' => '92', 'nama' => 'KAB. TELUK BINTUNI', 'email_info_penetapan' => null],
            ['id' => '9207', 'provinsi_id' => '92', 'nama' => 'KAB. TELUK WONDAMA', 'email_info_penetapan' => null],
            ['id' => '9208', 'provinsi_id' => '92', 'nama' => 'KAB. KAIMANA', 'email_info_penetapan' => null],
            ['id' => '9209', 'provinsi_id' => '92', 'nama' => 'KAB. TAMBRAUW', 'email_info_penetapan' => null],
            ['id' => '9210', 'provinsi_id' => '92', 'nama' => 'KAB. MAYBRAT', 'email_info_penetapan' => null],
            ['id' => '9211', 'provinsi_id' => '92', 'nama' => 'KAB. MANOKWARI SELATAN', 'email_info_penetapan' => null],
            ['id' => '9212', 'provinsi_id' => '92', 'nama' => 'KAB. PEGUNUNGAN ARFAK', 'email_info_penetapan' => null],
            ['id' => '9271', 'provinsi_id' => '92', 'nama' => 'KOTA SORONG', 'email_info_penetapan' => null]
        ];
        KabKota::query()->upsert($kabkot, 'id');
    }
}